#!/bin/bash

if [ $(id -u) -eq 0 ]
then
	echo "This scripts should be run as ubuntu"
	exit 1
fi

curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt install git curl wget python3-pip tmux nodejs vim -y

# Setup neovim
mkdir -p /home/ubuntu/.config/nvim
touch -p /home/ubuntu/.config/nvim/init.vim
echo "call plug#begin(has('nvim') ? stdpath('data') . '/plugged' : '~/.vim/plugged')" >> /home/ubuntu/.config/nvim/init.vim
echo "call plug#end()" >> /home/ubuntu/.config/nvim/init.vim

pushd /tmp
wget --quiet https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.deb
wget --quiet https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.deb.sha256sum

if ! sha256sum -c nvim-linux64.deb.sha256sum; then
	echo "Checksum failed" >& 2
	exit 1
fi
popd

sudo apt install "/tmp/nvim-linux64.deb"

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

pip3 install --user neovim
nvim --headless +PlugInstall +qa
